"""empty message

Revision ID: 9cfc58b1f627
Revises: 694c480d1c00
Create Date: 2023-03-08 15:33:07.551885

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '9cfc58b1f627'
down_revision = '694c480d1c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
