"""empty message

Revision ID: 5e20c7f4f39b
Revises: fefe806f4d86
Create Date: 2023-03-01 21:04:22.593933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '5e20c7f4f39b'
down_revision = 'fefe806f4d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
