"""empty message

Revision ID: 15b6e68c4783
Revises: f4f91dab2322
Create Date: 2023-03-15 18:07:33.692316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15b6e68c4783'
down_revision = 'f4f91dab2322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summoner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('puu_id')

    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summoner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_column('summoner_name')

    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puu_id', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('summoner_name')

    # ### end Alembic commands ###
