"""empty message

Revision ID: 7bf31c400d30
Revises: 9c853237393d
Create Date: 2023-03-01 21:31:25.614256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bf31c400d30'
down_revision = '9c853237393d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LOL_PROFILES', schema=None) as batch_op:
        batch_op.alter_column('last_updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('MATCH_HISTORIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MATCH_HISTORIES', schema=None) as batch_op:
        batch_op.drop_column('test')

    with op.batch_alter_table('LOL_PROFILES', schema=None) as batch_op:
        batch_op.alter_column('last_updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
