"""empty message

Revision ID: 1fab8361f209
Revises: 11f998766a67
Create Date: 2023-03-15 18:41:23.883131

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fab8361f209'
down_revision = '11f998766a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_column('summoner_name')

    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_column('summoner_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summoner_name', mysql.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summoner_name', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
