"""empty message

Revision ID: 694c480d1c00
Revises: 7bf31c400d30
Create Date: 2023-03-01 21:32:50.469820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '694c480d1c00'
down_revision = '7bf31c400d30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MATCH_HISTORIES', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MATCH_HISTORIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
