"""empty message

Revision ID: 9deb74a49dc2
Revises: 1fab8361f209
Create Date: 2023-03-15 18:43:36.887700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9deb74a49dc2'
down_revision = '1fab8361f209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('champion_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('champion_name_en')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MOST_CHAMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('champion_name_en', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('champion_name')

    # ### end Alembic commands ###
