"""empty message

Revision ID: d32b9261a99b
Revises: 899f3d9f6a85
Create Date: 2023-03-08 16:01:41.203211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'd32b9261a99b'
down_revision = '899f3d9f6a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
