"""empty message

Revision ID: 21908231903f
Revises: 9deb74a49dc2
Create Date: 2023-03-22 19:38:30.580463

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '21908231903f'
down_revision = '9deb74a49dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
