"""empty message

Revision ID: 9c853237393d
Revises: 5e20c7f4f39b
Create Date: 2023-03-01 21:06:33.511196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c853237393d'
down_revision = '5e20c7f4f39b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('manner_tier',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('curr_lol_account',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('profile_image_uri',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('profile_image_uri',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('curr_lol_account',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('manner_tier',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
