"""empty message

Revision ID: 83b9c80b40f6
Revises: d32b9261a99b
Create Date: 2023-03-08 19:13:48.521018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '83b9c80b40f6'
down_revision = 'd32b9261a99b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
