"""empty message

Revision ID: 98b71b11caca
Revises: 9cfc58b1f627
Create Date: 2023-03-08 15:33:57.716964

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '98b71b11caca'
down_revision = '9cfc58b1f627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
