"""empty message

Revision ID: fefe806f4d86
Revises: 4457cc2f09af
Create Date: 2023-03-01 20:24:18.247690

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'fefe806f4d86'
down_revision = '4457cc2f09af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
