"""empty message

Revision ID: 899f3d9f6a85
Revises: 98b71b11caca
Create Date: 2023-03-08 16:01:31.384452

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '899f3d9f6a85'
down_revision = '98b71b11caca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
