"""empty message

Revision ID: 0eae90578e09
Revises: 83b9c80b40f6
Create Date: 2023-03-15 09:30:53.496999

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '0eae90578e09'
down_revision = '83b9c80b40f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MOST_CAHMPION_SUMMARIES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_season_summary_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('MOST_CAHMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MOST_CAHMPION_SUMMARIES_id'), ['id'], unique=False)

    op.create_table('MOST_LINE_SUMMARIES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_season_summary_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MOST_LINE_SUMMARIES_id'), ['id'], unique=False)

    with op.batch_alter_table('CURRENT_SEASON_SUMMARIES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puu_id', sqlmodel.sql.sqltypes.AutoString(length=78), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CURRENT_SEASON_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_column('puu_id')

    with op.batch_alter_table('MOST_LINE_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MOST_LINE_SUMMARIES_id'))

    op.drop_table('MOST_LINE_SUMMARIES')
    with op.batch_alter_table('MOST_CAHMPION_SUMMARIES', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MOST_CAHMPION_SUMMARIES_id'))

    op.drop_table('MOST_CAHMPION_SUMMARIES')
    # ### end Alembic commands ###
